### ISSUE TITLE
doOnCompleted() is not called when using take() on an observable created with just()

### ISSUE THREAD

**Issue by jjagged** [ReactiveX/RxScala#145]
It seems that using `take()` prevents `doOnCompleted()` and related `doOnTerminate()` and `finallyDo()` to be called, but only if the observable was created with `just()` or `from(Iterable)`.

``` scala
  def obs(i: Int) = Observable.just(i)
    .doOnNext(n => println(s"next $i "))
    .doOnCompleted(println(s"completed $i "))
    .doOnTerminate(println(s"terminated $i "))
    .finallyDo(println(s"finally done $i "))

  val result1 = obs(1).single.toBlocking.head
  val result2 = obs(2).take(1).toBlocking.head
```

yields the result

```
next 1 
completed 1 
terminated 1 
finally done 1 
next 2 
```

"completed 2" etc. is never printed. However, the corresponding code in Java works as I thought it would,

``` java
    public static Observable<Integer> testObservable(final Integer i) {
        return Observable.just(i)
                .doOnNext(new Action1<Integer>() {
                    @Override
                    public void call(Integer integer) {
                        System.out.println("Next " + i);
                    }
                })
                .finallyDo(new Action0() {
                    @Override
                    public void call() {
                        System.out.println(("Finally do " + i));
                    }
                });
    }

    public static void main(String[] args) {
        Integer result1 = testObservable(1).take(1).toBlocking().single();
        System.out.println("Result is " + result1);
        Integer result2 = testObservable(2).single().toBlocking().single();
        System.out.println("Result is " + result2);
    }
```

yields the expected result

```
Next 1
Finally do 1
Result is 1
Next 2
Finally do 2
Result is 2
```

Are my expectations on `take` in rxscala wrong?

See https://github.com/jjagged/RxScalaTake for a Scala example and a corresponding Java example.

I'm using rxjava 1.0.6 and rxscala 0.23.1

**Comment by samuelgruetter** [comment]
Let me first explain why I think that Scala's behavior is correct, and Java's is "less correct": Calling `single` on an observable requires to run it until completion, to check if there were really not more elements than one, and so, the `doOnCompleted`, `doOnTerminate` and `finallyDo` handlers are all executed. However, `take(1)` can unsubscribe from the source observable as soon as it has received one element, so the source observable is never completed, and thus, its `doOnCompleted`, `doOnTerminate` and `finallyDo` handlers are never executed.

Now why is there a difference between Java's and Scala's behavior? It's because `Observable.just(i)` is implemented differently in Java and Scala:
-    Java has a [special case](https://github.com/ReactiveX/RxJava/blob/v1.0.6/src/main/java/rx/Observable.java#L1279) for a 1-arg `just`, where it uses a `ScalarSynchronousObservable`. As you can see in its [source](https://github.com/ReactiveX/RxJava/blob/v1.0.6/src/main/java/rx/internal/util/ScalarSynchronousObservable.java), it always calls `onCompleted()` without checking `isUnsubscribed` before. This is IMHO wrong, but as the comment says, it's done for performance reasons. So that's why it executes the `finallyDo` handler, even though I think it shouldn't.
-    Scala has no special case for 1-arg `just`, so as soon as `take(1)` unsubscribes, no more events are emitted, so the `finallyDo` handler is not executed, as I would expect.

To illustrate this, you can replace `Observable.just(i)` in Java by `Observable.from(Arrays.asList(Integer.valueOf(i)))`, and then Java behaves as Scala.

Regarding "less correct" in the first sentence: As far as I understand, the [Rx Design Guidelines](http://go.microsoft.com/fwlink/?LinkID=205219) allow both Java's and Scala's behavior, because they say in 4.4 to "assume a best effort to stop all outstanding work on Unsubscribe".

**Comment by jjagged** [comment]
I see, thanks for the explanation. Perhaps it would be beneficial to document this behaviour of `take` (and `head` and `first` that use `take`)?

**Comment by samuelgruetter** [comment]
Sure, pull requests to improve the docs are always welcome ;-) For the RxJava javadoc, RxScala scaladoc, or the [language-agnostic docs](http://reactivex.io/documentation/operators/take.html) (whose source is [here](https://github.com/ReactiveX/reactivex.github.io/blob/develop/documentation/operators/take.html))...
