### ISSUE TITLE
Unable to use pattern matching anonymous function for subscribe method

### ISSUE THREAD

**Issue by benedictleejh** [ReactiveX/RxScala#160]
When attaching an anonymous function to a subscribe method, I am unable to use a pattern matching anonymous function directly to destructure tuples. For example, the following code

``` scala
Observable.from(List((1,"one"), (2, "two"))) subscribe { case (i, s) =>
  println(s"int: $i, string: $s")
}
```

fails to compile with:

```
missing parameter type for expanded function
The argument types of an anonymous function must be fully known. (SLS 8.5)
Expected type was: ?
  Observable.from(List((1,"one"), (2, "two"))) subscribe { case (i, s) =>
```

Instead, it must either be written as

``` scala
Observable.from(List((1,"one"), (2, "two"))) subscribe { _ match {
    case (i, s) => println(s"int: $i, string: $s")
  } 
}
```

or

``` scala
Observable.from(List((1,"one"), (2, "two"))) subscribe { pair => 
  pair match {
    case (i, s) => println(s"int: $i, string: $s")
  }
}
```

I'm not sure if this is a limitation of Scala or of the way the API is written, but it would be nice to be able to resolve this. I don't know how common `Observable`s of tuples are, but being able to destructure them directly would be much appreciated.

**Comment by samuelgruetter** [comment]
The source of the problem is that `subscribe` is an overloaded method. Consider this:

``` scala
    class Obs[T] {
      def subscribe(onNext: T => Unit): Unit = ???
    }

    val o1: Obs[(Int, String)] = ???

    o1 subscribe {
      case (i, s) => println(s"int: $i, string: $s")
    }
```

It compiles without any problems. But as soon as we add an overload:

``` scala
    class Obs[T] {
      def subscribe(onNext: T => Unit): Unit = ???
      def subscribe(subscriber: Subscriber[T]): Unit = ???
    }
```

we get the same error as you got above. In my experience, Scala compiler folks view overloading as bad legacy inherited from Java, and there's not much motivation to improve `scalac`'s support for overloading.

So we would have to fix it in the RxScala API. But when designing the RxScala API, we still wanted to stay reasonably close to RxJava/Rx.NET, so eliminating or renaming all overloaded methods was not an option.

However, I think that's not too bad, because there are many ways to solve your problem:

First, note that most of the time, you shouldn't perform your logic in the `onNext` closure passed to `subscribe`, but already when you're still in the Observable chain, so you'd rather do something like this:

``` scala
    Observable.just((1, "one"), (2, "two")) map {
      case (i, s) => s"int: $i, string: $s"
    } subscribe (s => println(s))
```

Or use a for-comprehension (which is rewritten by the compiler to the same as the above snippet):

``` scala
    (for ((i, s) <- Observable.just((1, "one"), (2, "two")))
      yield s"int: $i, string: $s").subscribe(s => println(s))
```

Or if you want, you can also use `foreach`, which is an alias of `subscribe(T => Unit)`, but has no overload with the same number of parameters, so type inference works:

``` scala
    Observable.just((1, "one"), (2, "two")) foreach {
      case (i, s) => println(s"int: $i, string: $s")
    }
```

And again, you can write it as a for comprehension, and the compiler will rewrite it to the above:

``` scala
    for ((i, s) <- Observable.just((1, "one"), (2, "two"))) {
      println(s"int: $i, string: $s")
    }
```

Does that make sense?

**Comment by benedictleejh** [comment]
Yes, thanks so much for your help. It was nice to see that there are solutions availble so that I can still destructure tuples instead of resorting to an explicit match.

The comment that I should be doing most of the processing in the Observable chain was very enlightening, and has really helped me understand how to use Rx a bit better, and allowed me to handle my Observables in a cleaner way.
