### ISSUE TITLE
Need README

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#2]
This project needs a README for the base page. I chose not to just move the README from the subfolder since it is serving more as documentation rather than the entry point for the project. 

We'll need something similar to https://github.com/ReactiveX/RxJava/blob/1.x/README.md

**Comment by headinthebox** [comment]
Yup. The previous README was more of a design doc.

**Comment by EugeneLoy** [comment]
Also requesting instructions on how to build the project.
Checked out the sources today and can't figure it out how to put everything together (due to unsatisfied dependency on `rxjava-core` whitch is now missing in `RxJava`'s master, though I am a Gradle newbie, so it is possible that I am derping something).
As far as I've understood `RxScala` were factored out from `RxJava` repo recently, so I am assuming I am experincing problems because the build structure has not been adapted yet.
Anyway, having some guidelines explaining how to build project now would be helpful.

**Comment by zsxwing** [comment]
@EugenyLoy RxScala was just extracted from RxJava. We are still working on the migration.

**Comment by zsxwing** [comment]
@EugenyLoy you can use a temporary build.gradle to build RxScala in my repo: https://github.com/zsxwing/RxScala/blob/rxscala-operators/build.gradle. It only supports building and generating an IntelliJ project.

**Comment by EugeneLoy** [comment]
@zsxwing thanks, it worked for me.

**Comment by jmhofer** [comment]
I just updated the information about building in the readme. It's now standard sbt.
