### ISSUE TITLE
Can someone advise me the need of this library?

### ISSUE THREAD

**Issue by wihoho** [ReactiveX/RxScala#241]
Why RxScala is created since Scala almost `natively` supports features brought by this RxScala?

Just curious on the intention. Thanks.

**Comment by dhoepelman** [comment]
RxJava/RxScala was a precursor to [Reactive Streams](http://www.reactive-streams.org/), which has since become part of the JVM. Other libraries built upon these interfaces to provide similar streaming frameworks.

At the moment of writing, Scala or its standard library does not natively support this asynchronous non-blocking streaming.
