### ISSUE TITLE
Observable.range() operator is missing

### ISSUE THREAD

**Issue by gkhom** [ReactiveX/RxScala#26]
We should add the operators that Iterable has to Observable as well, to make them match up.

**Comment by samuelgruetter** [comment]
The [comparison table](http://reactivex.io/rxscala/comparison.html) explains why `Observable.range()` is missing.
You can do this:

``` scala
(1 to 10).toObservable.subscribe(println(_))
Observable.from(1 to 10).subscribe(println(_))
```

and I think that's sufficient. Don't you?

**Comment by gkhom** [comment]
That makes sense. But isn't there some (small) overhead in creating the `Range` first?

**Comment by samuelgruetter** [comment]
Maybe ;-) But that overhead is really small, because the `Range` object just stores the first and the last number and the step size, without storing all numbers inbetween.

**Comment by headinthebox** [comment]
I think it would be nice to add it.

**Comment by samuelgruetter** [comment]
Why? Because you think an API of 325 operators is not yet big enough, and it would be nice to add yet another way of doing the same ;-)
What I find nice is that `Range` is a subtype of `Iterable`, which allows us to use the same method for two things which need different ones in Java. Don't you see the beauty and power of the abstraction ;-)

**Comment by headinthebox** [comment]
I have absolutely no sense of abstract.

**Comment by headinthebox** [comment]
All jokes and arguments about orthogonal bases aside, I do think consistency between `Iterable.XXX` and `Observable.XXX` whenever it makes sense is something to strive for. In fact, in .NET we back ported several method of `IObservable` back to `IEnumerable`. In fact, this is the only exception I make when considering adding new operators. Also, another argument is that it is a standard Rx operator http://msdn.microsoft.com/en-us/library/hh211896(v=vs.103).aspx

**Comment by samuelgruetter** [comment]
> I do think consistency between `Iterable.XXX` and `Observable.XXX` whenever it makes sense is something to strive for.

+1

But I see a problem: The arguments of `range` in Scala's Iterable are `start` and `end`, but in Java's Observable, it's `start` and `count`. So, whichever of these two we chose, people will say we did it wrong...

**Comment by headinthebox** [comment]
Agree; I _much_ prefer Scala's choice. Alway mess up with the count thing.

**Comment by samuelgruetter** [comment]
Here's how I would "solve" this issue: https://github.com/ReactiveX/RxScala/pull/38

**Comment by leonidv** [comment]
up vote this issue. I think the best way is add Observable.range into rxScala, because this is standard Rx operator, and add into ScalaDoc of this operator information about another solutions from http://reactivex.io/rxscala/comparison.html

I spend about 30 minutes to found how to use range in rxScala.

**Comment by samuelgruetter** [comment]
But at least now you know that there's a comparison table which can help you find the operator you need ;-)

Can you give us an idea how to make http://reactivex.io/rxscala/comparison.html more discoverable?

**Comment by dhoepelman** [comment]
Due to project EOL status, no new operators will be implemented.
