### ISSUE TITLE
Naming when importing RxJava classes

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxScala#41]
A suggestion for the code style: rename `XXX` to `JXXX` when importing a class from RxJava. This would improve the code readability and follow the style of Scala collection codes.

**Comment by samuelgruetter** [comment]
+1

But in [JavaConversions](https://github.com/ReactiveX/RxScala/blob/0.x/src/main/scala/rx/lang/scala/JavaConversions.scala) and [ImplicitFunctionConversions](https://github.com/ReactiveX/RxScala/blob/0.x/src/main/scala/rx/lang/scala/ImplicitFunctionConversions.scala) I would not do that, because they're exposed to the users, so they should keep the whole name.
And I would only do the renaming if `XXX` also exists in Scala, so I'd not rename `Func1` into `JFunc1`.

**Comment by headinthebox** [comment]
Mmm, smells too much like http://en.wikipedia.org/wiki/Hungarian_notation to me.

**Comment by dhoepelman** [comment]
Due to project EOL status, this has become irrelevant.
