### ISSUE TITLE
About TODO.md

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxScala#76]
@samuelgruetter could you review `TODO.md`? I think now we can create issues for the unfinished TODOs and remove `TODO.md`, since RxScala it's a separate project.

**Comment by samuelgruetter** [comment]
I looked through `TODO.md`, and I think these two issues is what we need to keep: https://github.com/ReactiveX/RxScala/issues/77 and https://github.com/ReactiveX/RxScala/issues/78.
Does anyone think there's something else we should keep? If so, please add an issue. Otherwise we can delete `TODO.md`.

**Comment by zsxwing** [comment]
Removed TODO.md in #89
