### ISSUE TITLE
rx.schedulers.Schedulers.from(Executor)

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#77]
Should we add a Scala equivalent for `rx.schedulers.Schedulers.from(Executor)`? Would it take a `scala.concurrent.ExecutionContext`? And what's the relation/difference between a Java `Executor` and a Scala `ExecutionContext`?

**Comment by headinthebox** [comment]
>  And what's the relation/difference between a Java Executor and a Scala ExecutionContext?

I always wondered about that; why did Scala no reuse the standard Java executors?

**Comment by jbripley** [comment]
I think we should add it. It would allow someone to run Scala Futures and Observables against the same underlying thread pool, which I imagine could be useful.

**Comment by zsxwing** [comment]
> And what's the relation/difference between a Java Executor and a Scala ExecutionContext?
> And somehow, Java and Scala are compatible, can we exploit this better? 

Scala `ExecutionContextImpl` uses `Java Executor`: https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/impl/ExecutionContextImpl.scala#L27 but we cannot get it via any public API, that's why I created a `Java Executor` wrapper for `Scala ExecutionContext`.

> And do we also have to care about ExecutorServices?

Because Scala doesn't have something like `Java ScheduledExecutorService`, we can ignore `ScheduledExecutorService`. Therefore in RxJava, `ExecutorScheduler` only uses `Executor.execute`: https://github.com/ReactiveX/RxJava/blob/fa927ab79f1996e7b13caa3b79d7f96be86856d4/src/main/java/rx/schedulers/ExecutorScheduler.java#L81 ,so we don't need to care about `ExecutorService`.

**Comment by zsxwing** [comment]
Fixed in #91
