### ISSUE TITLE
Observable error

### ISSUE THREAD

**Issue by headinthebox** [ReactiveX/RxScala#80]
```
def error[T](exception: Throwable): Observable[T] = {
    toScalaObservable[T](rx.Observable.error(exception))
  }
```

This can return `Observbale[Nothing]` like `empty` and `never` or not?

**Comment by samuelgruetter** [comment]
Yes it can, because if no type parameter for `T` is given, the compiler infers the most precise type possible, which is `Nothing`:

``` scala
val o1 = Observable.error(new Exception())      // creates an Observable[Nothing]
```

**Comment by samuelgruetter** [comment]
Oops, looks like I misunderstood the question, and then you misunderstood my answer.

I understood the question as "Can we use `Observable.error` _as if_ it was defined without a type parameter and returning `Observable[Nothing]`"? And the answer to this question is yes.

But I would keep the additional type parameter in the current signature, because it has the advantage that we can give the desired type parameter explicitly if we wish to do so, which often improves type inference, as @zsxwing's example in https://github.com/ReactiveX/RxScala/pull/83 shows.

**Comment by zsxwing** [comment]
I think `empty`, `never` and `error` have the same problem: should we use `Observable[Nothing]`?

I tend to `yes` and prefer to make these methods consistent because:
- It's much like `Nil`. `Nil` also has similar problem. E.g.,

``` Scala
val o: List[Int] = Nil.map(v => v)
val x = 1
println(x + (Nil.head: Int))
val y: Int = Nil.head
```
- My examples in #83 are contrived. I don't think people will write such codes. When they use `empty`, `never` or `error`, they usually have some other Observable with a known type parameter in hand and combining these `Observable`s will work well with type inference.

**Comment by samuelgruetter** [comment]
I agree that we should make `empty`, `never` and `error` consistant. But I'd prefer adding type params to all of them because:

1) Scala's `List.empty` does so as well:

``` scala
def empty[A]: List[A] 
```

2) There's no program which stops working if we add type parameters, but some stop working if we remove them.

3) This is a chance to help users when Scala's type inference is not smart enough.

**Comment by zsxwing** [comment]
Great points. I'm convinced.

**Comment by headinthebox** [comment]
Disagree. I absolutely hate to see any types. It is super irritating to be forced to specify the type in error. We should leverage covariance.

As long as we are not at 1.0 we _should_ break people as we iterate towards a stable API.

**I'll veto the change to add type parameters.**

**Comment by zsxwing** [comment]
@headinthebox 

Scala used `List[Nothing]` before. But @odersky changed it to `List[A]` in

https://github.com/scala/scala/commit/14a631a5fec42d04d0723355a0b93e482b5e4662#diff-65c966843f6b3b817df43968f326d160L580

`override val empty: List[Nothing] = Nil` => `override def empty[A]: List[A] = Nil`

**Comment by headinthebox** [comment]
i'll check with Martin.

**Comment by zsxwing** [comment]
@headinthebox any update?

**Comment by zsxwing** [comment]
ping @headinthebox

**Comment by zsxwing** [comment]
@headinthebox this is still pending...

**Comment by headinthebox** [comment]
I pinged Martin.

**Comment by odersky** [comment]
Not sure what the question is?

On Tue, May 5, 2015 at 5:34 PM, headinthebox notifications@github.com
wrote:

> I pinged Martin.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ReactiveX/RxScala/issues/80#issuecomment-99117755.

## 

Martin Odersky
EPFL and Typesafe

**Comment by odersky** [comment]
read the mails in the wrong order - now I saw Erik's question.

List[Nothing] is preferable if everything is covariant. But in this
particular case, empty overrides/implements a method with a very general
collection type that does not assume
the collection is covariant. So we have to fall back to polymorphism here.
- Martin

On Tue, May 5, 2015 at 5:57 PM, martin odersky odersky@gmail.com wrote:

> Not sure what the question is?
> 
> On Tue, May 5, 2015 at 5:34 PM, headinthebox notifications@github.com
> wrote:
> 
> > I pinged Martin.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ReactiveX/RxScala/issues/80#issuecomment-99117755.
> 
> ## 
> 
> Martin Odersky
> EPFL and Typesafe

## 

Martin Odersky
EPFL and Typesafe

**Comment by headinthebox** [comment]
Note Observable[T] is absolutely covariant (which is why I made it Observable[Nothing] to leverage that fact). The argument in favor of using polymorphism I heard is that you can if you want specify the element type.

**Comment by odersky** [comment]
Is Observable covariant? If yes, Observable[Nothing] is preferable.
- Martin

On Tue, May 5, 2015 at 6:01 PM, headinthebox notifications@github.com
wrote:

> Which is preferred empty: Observable[Nothing] or empty[T]: Observable[T].
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ReactiveX/RxScala/issues/80#issuecomment-99124668.

## 

Martin Odersky
EPFL and Typesafe

**Comment by headinthebox** [comment]
OK, thanks ;-)

**Comment by zsxwing** [comment]
> Is Observable covariant? If yes, Observable[Nothing] is preferable.

@odersky the confusing thing here is that `immutable.List` is covariant too. But it uses [override def empty[A]: List[A] = Nil](https://github.com/scala/scala/blob/1d4a1f721d360c73b9f2468368c7e9b2b4c17fea/src/library/scala/collection/immutable/List.scala#L455)

**Comment by zsxwing** [comment]
And the following codes can pass the compiler (2.10.4):

``` Scala
import scala.collection.generic.SeqFactory
import scala.collection.mutable

object Foo extends SeqFactory[List] {

  override def empty[Nothing] = Nil

  override def newBuilder[A]: mutable.Builder[A, List[A]] = ???
}
```
